import "server-only";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { PDFDocument, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";

/** Pediatrician-friendly visit summary (spec §24). Allergies always on page 1; sources appendix; identity block on every page. */
type Any = Record<string, unknown>;
const INK = rgb(0.12, 0.23, 0.24), MUTED = rgb(0.33, 0.41, 0.42), SAGE = rgb(0.25, 0.44, 0.35), ALLERGY = rgb(0.62, 0.18, 0.23), LINE = rgb(0.9, 0.87, 0.83);
const COLOUR: Record<string, [number, number, number]> = { PEACH: [0.96, 0.78, 0.69], SKY: [0.75, 0.85, 0.93], MINT: [0.78, 0.9, 0.83], LILAC: [0.85, 0.8, 0.94], BUTTER: [0.96, 0.89, 0.65], ROSE: [0.94, 0.77, 0.81] };

export async function visitSummaryPdf(input: { baby: Any; summary: Any; generatedAt: string; generatedBy: string; sources: Any[] }) {
  const doc = await PDFDocument.create();
  doc.registerFontkit(fontkit);
  const dir = join(process.cwd(), "assets", "fonts");
  const font = await doc.embedFont(await readFile(join(dir, "WorkSans-Regular.ttf")), { subset: true });
  const bold = await doc.embedFont(await readFile(join(dir, "WorkSans-Bold.ttf")), { subset: true });
  doc.setTitle("Visit summary"); doc.setAuthor(""); doc.setSubject(""); doc.setKeywords([]); doc.setProducer("Baby Health"); doc.setCreator("Baby Health");
  const W = 595.28, H = 841.89, M = 48;
  let page!: PDFPage, y = 0, pageNo = 0;
  const b = input.baby, s = input.summary;
  const safe = (t: unknown, f: PDFFont) => String(t ?? "").split("").map((ch) => (f.getCharacterSet().includes(ch.codePointAt(0)!) ? ch : "?")).join("");

  const header = () => {
    page = doc.addPage([W, H]); pageNo++; y = H - M;
    const [r0, g0, b0] = COLOUR[String(b.colour_token)] ?? [0.86, 0.92, 0.88];
    page.drawRectangle({ x: 0, y: H - 10, width: W, height: 10, color: rgb(r0, g0, b0) });
    page.drawText(safe(`${b.first_name}${b.nickname ? ` (${b.nickname})` : ""}`, bold), { x: M, y, size: 16, font: bold, color: INK });
    page.drawText(safe(`DOB ${b.birth_date} · ${String(b.sex).toLowerCase().replace("_", " ")} · ${(b.age as Any)?.display ?? ""}`, font), { x: M, y: y - 16, size: 9.5, font, color: MUTED });
    page.drawText(safe(`${s.period} · ${s.from} to ${s.to}`, font), { x: W - M - 200, y, size: 9.5, font, color: MUTED });
    y -= 36;
    page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 0.6, color: LINE });
    y -= 16;
    page.drawText(safe(`Generated by Baby Health from parent-entered records on ${input.generatedAt}. Not a clinical record. Page ${pageNo}`, font), { x: M, y: 24, size: 7.5, font, color: MUTED });
  };
  const ensure = (h: number) => { if (y - h < 50) header(); };
  const wrap = (text: string, f: PDFFont, size: number, width: number) => {
    const words = safe(text, f).split(/\s+/); const lines: string[] = []; let cur = "";
    for (const w of words) { const t = cur ? `${cur} ${w}` : w; if (f.widthOfTextAtSize(t, size) > width && cur) { lines.push(cur); cur = w; } else cur = t; }
    if (cur) lines.push(cur); return lines;
  };
  const para = (text: string, opts: { size?: number; f?: PDFFont; color?: ReturnType<typeof rgb>; indent?: number } = {}) => {
    const size = opts.size ?? 9.5, f = opts.f ?? font;
    for (const line of wrap(text, f, size, W - 2 * M - (opts.indent ?? 0))) { ensure(size + 4); page.drawText(line, { x: M + (opts.indent ?? 0), y, size, font: f, color: opts.color ?? INK }); y -= size + 4; }
  };
  const h2 = (t: string) => { ensure(30); y -= 6; page.drawText(safe(t, bold), { x: M, y, size: 11.5, font: bold, color: SAGE }); y -= 16; };

  header();
  // Allergies first (spec §29)
  const allergies = (s.allergies as Any[]) ?? [];
  page.drawRectangle({ x: M, y: y - 34, width: W - 2 * M, height: 40, color: rgb(0.98, 0.89, 0.89) });
  page.drawText("Allergies", { x: M + 10, y: y - 12, size: 10.5, font: bold, color: ALLERGY });
  const at = allergies.length ? allergies.map((a) => `${a.substance} (${a.status === "CONFIRMED_BY_DOCTOR" ? "confirmed" : "suspected"}${a.severity_reported !== "UNKNOWN" ? `, ${String(a.severity_reported).toLowerCase()} reported` : ""})`).join("; ")
    : (b.nka_confirmed_at ? "No known allergies (confirmed by parent)" : "No allergies recorded");
  page.drawText(safe(at, font).slice(0, 110), { x: M + 10, y: y - 26, size: 9.5, font, color: INK });
  y -= 52;

  const f = s.feeding as Any;
  h2("Feeding (recorded)");
  para(`Feeds recorded: ${f.totalFeeds} over ${f.daysWithAnyData} day(s) with data (${(f.days as unknown[]).length} day(s) in period). Average feeds per day with data: ${f.feedsPerDayAvg ?? "not available"}.`);
  para(`Direct breastfeeding sessions: ${f.directBreastfeedingSessions} (not converted to volume).`);
  para(`Measured milk (expressed breast milk + formula): ${f.totalMeasuredMl != null ? `${f.totalMeasuredMl} ml total; ${f.avgMeasuredMlPerDayWithData} ml/day averaged over ${f.daysWithMeasuredData} day(s) with measured feeds` : "not available"}.`);
  if (f.median_interval_min) para(`Median interval between recorded feeds: ${f.median_interval_min} min.`);
  const ref = s.reference as Any;
  para(`Reference status: ${ref?.reference_status}. ${((ref?.messages as string[]) ?? []).join(" ")}`, { color: MUTED, size: 8.5 });
  // compact per-day table
  ensure(20);
  const days = (f.days as Any[]).filter((d) => d.dataStatus === "RECORDED");
  if (days.length) {
    para("Day · feeds · BF sessions · measured ml", { f: bold, size: 8.5 });
    for (const d of days.slice(-31)) para(`${d.localDate} · ${d.totalFeedCount} · ${d.directBreastfeedingSessions} · ${d.measuredMl ?? "—"}`, { size: 8.5, indent: 8 });
  }

  h2("Growth (recorded measurements)");
  const ws = (s.weights as Any[]) ?? [];
  if (!ws.length) para("No measurements recorded in this period.");
  for (const w of ws) para(`${w.local_date}: ${[w.weight_kg != null && `${w.weight_kg} kg`, w.length_cm != null && `length ${w.length_cm} cm`, w.head_circumference_cm != null && `HC ${w.head_circumference_cm} cm`].filter(Boolean).join(", ")} (${String(w.measurement_source).toLowerCase().replace("_", " ")})`, { indent: 8 });
  const wt = s.weight_trend as Any | null;
  if (wt) para(`Weight change: ${wt.delta_g} g over ${wt.days} day(s).`);

  h2("Vaccinations");
  const vac = (s.vaccinations as Any[]) ?? [];
  if (!vac.length) para("None recorded in this period.");
  for (const v of vac) para(`${v.given_on}: ${v.vaccine_name_as_recorded}${v.dose_label ? ` (${v.dose_label})` : ""}`, { indent: 8 });
  const plan = s.vaccine_plan as Any | null;
  if (plan && (plan.due as Any[]).length) para(`Due per selected schedule (${plan.schedule_id}): ${(plan.due as Any[]).map((d) => d.dose_label).join(", ")}`, { color: MUTED });

  h2("Appointments");
  const ap = (s.appointments as Any[]) ?? [];
  if (!ap.length) para("None in this period.");
  for (const a of ap) para(`${new Date(String(a.starts_at)).toISOString().slice(0, 16).replace("T", " ")} UTC · ${String(a.purpose).toLowerCase().replace("_", " ")} · ${a.status}${a.doctor_name ? ` · ${a.doctor_name}` : ""}`, { indent: 8 });

  h2("Medicines (as recorded by parent; doses as prescribed)");
  const meds = (s.medicines as Any[]) ?? [];
  if (!meds.length) para("None recorded.");
  for (const m of meds) para(`${m.medicine_name} · ${m.status} · from ${m.start_date}${m.end_date ? ` to ${m.end_date}` : ""} · doses marked given: ${m.doses_given}`, { indent: 8 });

  h2("Medical documents");
  const docs = (s.documents as Any[]) ?? [];
  if (!docs.length) para("None in this period.");
  for (const d of docs) para(`${d.document_date ?? "undated"} · ${d.title} (${String(d.doc_type).toLowerCase().replace("_", " ")})`, { indent: 8 });

  h2("Timeline highlights");
  for (const e of ((s.highlights as Any[]) ?? []).slice(0, 15)) para(`${new Date(String(e.occurred_at)).toISOString().slice(0, 10)} · ${e.title}`, { indent: 8 });

  h2("Data quality");
  for (const n of (s.data_quality_notes as string[]) ?? []) para(n, { indent: 8 });

  h2("Sources of reference information");
  if (!input.sources.length) para("No medical reference values were displayed in this summary.");
  for (const src of input.sources) para(`${src.organization} — ${src.document_title} (${src.publication_date}). ${src.source_url}`, { size: 8, indent: 8, color: MUTED });
  para("Reference information only; not a substitute for pediatric care.", { size: 8, color: MUTED });
  return Buffer.from(await doc.save());
}
